### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by ifryan** [alangrainger/share-note#101]
### Discussed in https://github.com/alangrainger/share-note/discussions/98

<div type='discussions-op-text'>

<sup>Originally posted by **ifryan** April 30, 2024</sup>
the Latex formula show nothing on the shared page 
[check out this link]( https://share.note.sx/govcrsta#cKusFPXUQ2ZN197cvwfOhDi65yT5oYTJPOk24FGo88A)</div>

**Comment by alangrainger** [comment]
Hi, did you follow the steps in the docs?

https://docs.note.sx/troubleshooting#mathjax--latex

Here's what your code looks like after following those steps:

https://share.note.sx/wfl5qxii#j+bzbjvejUgj/axz38+K00zrQJ1zkZaoJisVnICUCm4

**Comment by ifryan** [comment]
@alangrainger 
it works, Thanks very much
