### ISSUE TITLE
{   "code": "not_found",   "message": "File with such name does not exist.",   "status": 404 }

### ISSUE THREAD

**Issue by mitchmeister** [alangrainger/share-note#107]
I followed the [Troublehooting tips](https://github.com/alangrainger/share-note/blob/main/docs/Troubleshooting.md) but they didn't help.  I am regularly getting this error.

Any suggestions?

**Comment by alangrainger** [comment]
Can you share any details at all? What are you doing when you get this message? I could guess that you're sharing, but maybe not, maybe you're trying to delete a note. If sharing, are you doing it from the command palette or the icon? A screenshot would be helpful too.

**Comment by mitchmeister** [comment]
Here is the URL

https://share.note.sx/qaluef3o/dv1nwT2OW2hrSOABeT4uHry984W3YDU+TW/cOJ0o9k

If you click on it you will get this message as json

```
{
  "code": "not_found",
  "message": "File with such name does not exist.",
  "status": 404
}
```

I have tried various ways of re-sharing the note (ie. updating) 
* the Share Note Property icon, 
* the Command palette `Share current note` and 
* the Command palette `Force reupload of all data for this note`.

**Comment by mitchmeister** [comment]
In looking at another note that I just shared I just noticed there was no `#` in that URL of the note I shared.  So I went back to the note I found that the Share_link had been updated.  It now reads

https://share.note.sx/qaluef3o#e7mmochVVSnQltM8UoZoWk4MS8boazQNQRrm/+F3/90

I'm not sure when and what happened to cause this, but I have had the same "not_found" with lots of other notes when reuploading them with "Share current note".

**Comment by mitchmeister** [comment]
@alangrainger have you got everything you need for debugging purposes; I want to delete this public note.

PS. Appreciate your help; your plugin is invaluable for adhoc sharing of notes.  In this instance I'm using it to share a task list with a developer I'm working with which otherwise I would have to manually recreate in Github or something like that.

**Comment by mitchmeister** [comment]
PS. I 've found a bunch more of my notes that don't have a `#` in the sharelink.

**Comment by mitchmeister** [comment]
Just been doing from more debugging of what is happening.

1. I click the up-arrow icon on share_link
2. I wait until it says "The note has been uploaded & link copied to your clipboard"
3. I go to my browser & paste the clipboard into the address bar.  All good; note is there.  
4. I go back to Obsidian.  I click on the tab of another note in Obsidian.
5. I then click back to the first note.  The share_link URL has changed; there is no longer a hash in it.

**Comment by alangrainger** [comment]
@mitchmeister that's brilliant - thank you so much for doing that debugging!

I am unable to replicate this in a Sandbox vault. It may be that you have some other plugin which is causing this, so can you please open the Sandbox vault and do the same test?

**Comment by mitchmeister** [comment]
@alangrainger what do you mean by a Sandbox vault?

**Comment by alangrainger** [comment]
1. Click on the Help icon and open Sandbox vault.
2. Install just the Share Note plugin.
3. Perform your same test as before.

![image](https://github.com/alangrainger/share-note/assets/16197738/1cc55e97-e222-4b6a-883e-5eb96acb6b67)

**Comment by mitchmeister** [comment]
Worked fine in Sandbox.  I guess I'll turn off each of my plugins in turn & test.  Will let you know if I find anything.  Thanks @alangrainger

**Comment by alangrainger** [comment]
Start with any linting plugins you might have. Seems like a strong candidate as the editing of your note (to remove the `#`) happened on changing notes.

**Comment by mitchmeister** [comment]
Bang on! Turning off Linter seems to remedy it.  Damn.  I'll find it hard to live without.

**Comment by mitchmeister** [comment]
Raised issue in Linter at https://github.com/platers/obsidian-linter/issues/1102

**Comment by alangrainger** [comment]
I use the Linter plugin also, without any issues.

I suggest you add the `share_link` property into the "YAML keys to ignore" section, or try unchecking the box to remove hashtags:

![image](https://github.com/alangrainger/share-note/assets/16197738/cd22a365-d5d1-483e-8851-3a3f75620555)

**Comment by mitchmeister** [comment]
:-) Thank you
