### ISSUE TITLE
Images work upon upload, but a week later 40% of them error in the shared note 

### ISSUE THREAD

**Issue by kleenkanteen** [alangrainger/share-note#109]
Will do the below later but wondering if anyone else had a similar issue. Force reuploadng did fix the issue. But I fear it may happen again in the future.

My example note, scroll to the middle to see those ones break: https://share.note.sx/dm5djtya#zxNarlHVoq52kaFmCwnRQ+xuPjbjcMUO15OWU9ka2Ak

To do later:
- If it still doesn't work, please create a demo vault with the plugins/themes needed to make this issue occur.
- Once you've created the demo vault, zip it up and upload as an attachment with this issue request.

**Comment by alangrainger** [comment]
I don't know if this is the issue, I can see from the page source that your image locations in your original note are specified in this format:

```
.../Sabih's%20Note%20Garden/Pasted%20image%2020240203182131.png?1707002491442
```

with the `?1707002491442` after the image filename.

Can you try removing that and see if it solves things?

**Comment by alangrainger** [comment]
Closing until feedback from kleenkanteen.
