### ISSUE TITLE
Deleting did not delete my Note

### ISSUE THREAD

**Issue by nny57** [alangrainger/share-note#110]
I deleted a file on Obsidian, the links and the properties were removed but when I try the web link, I am still able to see the file. The URL is: 
- https://share.note.sx/30soxrpq

I created another file to share and deleted and this time it looks like the file was deleted. 

- Can you delete the file so that it is no longer available?
- How can we know that a delete is actually going through on the server?

**Comment by alangrainger** [comment]
To delete a shared file you need to click the delete/trash icon on that note.

If you delete the Obsidian note it won't delete the shared note.

> How can we know that a delete is actually going through on the server?

If you're concerned about that, just share your notes encrypted. The decryption key isn't sent to the server (which you can verify from the plugin source code), so once you delete the decryption key at your end, it's gone.
