### ISSUE TITLE
warning message disappears too quickly

### ISSUE THREAD

**Issue by ksdavidc** [alangrainger/share-note#111]
The warning message when uploading that tells us not to move away from the page disappears too quickly to be read, and in fact I am not exactly sure what it is telling me to do.

**Comment by alangrainger** [comment]
You only need to stay on the note while the message is showing, so if it disappears too fast to read, you can safely ignore it.

I could change the message to read _"If this message is showing, please do not change to another note as the current note data is still being parsed."_ which might help?

**Comment by ksdavidc** [comment]
Thanks. I never got a good look at the original but yeah that would work
