### ISSUE TITLE
date fields never seem to display anything other than dd/mm/yy

### ISSUE THREAD

**Issue by mitchmeister** [alangrainger/share-note#114]
All of my date fields display like this 

### Shared note
<img width="379" alt="SCR-20240628-jqqy" src="https://github.com/alangrainger/share-note/assets/6250875/484c2037-7138-4ef4-91cb-233abb1513cd">

### Obsidian note
<img width="362" alt="SCR-20240628-jrdg" src="https://github.com/alangrainger/share-note/assets/6250875/38cb161d-3ec4-4426-8499-34670f25f94a">

### Source view
<img width="269" alt="SCR-20240628-jrst" src="https://github.com/alangrainger/share-note/assets/6250875/d096273e-77c7-461f-b22d-e0809df75f1a">

I just noticed that duration is missing too.

**Comment by alangrainger** [comment]
This is (mostly?) resolved in 0.8.14. 

There may be some niche cases which have to be handled manually, as Obsidian does some annoying non-compliant-HTML fuckery here.

**Comment by mitchmeister** [comment]
🙏🏻 thanks Alan
