### ISSUE TITLE
Can't share a note

### ISSUE THREAD

**Issue by Pixelgobbo** [alangrainger/share-note#117]
I do think I am at fault for creating my issue.. I shared one note successfully already. Then I wanted to delete the link, just to see if I can figure out how. In case I need to do it in future or something. And honestly I don't remember what I did, I do know tho that it didn't feel right and now I can't share any of my notes anymore.
I wish I could give more information but I truely can't figure out what exactly the problem is. Everytime I try and share a note there is the same error message that something went wrong and I should try again. I deleted and reinstalled the plugin two times already (I am a bit desperate).
It also doesnt work on completely new and empty notes. 
Help?
I would be open to a call so I can demonstrate the issue and stuff, if this is too abstract.

**Comment by alangrainger** [comment]
Sorry about that, was a server issue. Can you try again - should be working now.

**Comment by Pixelgobbo** [comment]
Yeah all good now! Man I really tought I broke something haha

**Comment by CornflakesOnGit** [comment]
I'm hoping there is another server issue right now..
In a sandbox vault, I can share notes, but in my actual vault, I get "Share Note: There was an error uploading the note. Please try again."

I have no idea how to go about fixing it 🙃

**Comment by alangrainger** [comment]
@CornflakesOnGit good to know, thank you. I can imagine that might cause issues - I will test it out.
