### ISSUE TITLE
Hello developers!

### ISSUE THREAD

**Issue by siriusacma** [alangrainger/share-note#126]
Everything was normal but today i get this error when i trying upload a note. What should i do? I relaunched Obsidian and plugin and it didn't any changes on this issue.
<img width="317" alt="image" src="https://github.com/user-attachments/assets/22dce913-d747-4350-83a8-c718c056b04e">

**Comment by alangrainger** [comment]
Sorry about that - server error - all working now, please try again :)

**Comment by siriusacma** [comment]
Many many thanks! 🤗 You created the greatest plugin for Obsidian!
