### ISSUE TITLE
Local export as HTML

### ISSUE THREAD

**Issue by Mara-Li** [alangrainger/share-note#135]
## Idea
I wanted a way to create PDF on my iPad, and the only idea I had it was to export it as HTML. I tried to recreate your plugin but “as local” (so simpler), but I got stuck with the view-port part. 
As your plugin is FAAAAAAR up than mine (as you already patched all problem with the “get HTML from obsidian”), I would to know if it is possible to add a feature to get the HTML instead of upload it.

You can do it as “download”. For example, we can use:
```ts
const fileName = file.basename;
const blob = new Blob([htmlContent], { type: "text/html" });
const url = URL.createObjectURL(blob);
const a = document.createElement("a");
a.href = url;
a.download = `${fileName}.html`;
document.body.appendChild(a);
a.click();
document.body.removeChild(a);
URL.revokeObjectURL(url);
```

I would like to push, maybe, a PR to this plugin, but I don't understand entirely the plugin and don't know if it is possible to separate the uploading process with the HTML process, as maybe some CSS rely on the server. In my idea, the CSS needs to be embedded in the file (and this can be tricky, as the CSS can be enormous)

**Comment by alangrainger** [comment]
Please add feature requests on the [Feature Requests](https://github.com/alangrainger/share-note/discussions/categories/vote-for-upcoming-features?discussions_q=is%3Aopen+category%3A%22Vote+for+upcoming+features%22+sort%3Atop) page.

However I can say this one is unlikely, as the HTML output by this plugin is only partial, and requires being combined with [a template](https://github.com/alangrainger/share-note-self-hosted-backend/blob/main/api/note-template.html) on the server end.
