### ISSUE TITLE
Sharing API settings sync issues

### ISSUE THREAD

**Issue by thecodechemist99** [alangrainger/share-note#137]
I use obsidian on three devices:
- a Mac running MacOS 14.7.1,
- a laptop running Arch Linux,
- my iPhone running iOS 17.7.1

and I use obsidian sync to sync my vault between all three devices, with no directories excluded. Unfortunately, this doesn’t seem to sync the share-note API settings. I noticed they were synced between the Mac and laptop at some point, but after some experimentation now they are out of sync again. And the iPhone never synced the API settings with any of the other devices.

I looked up the data.json files as suggested in #66. Unfortunately I couldn’t find one in the vault from the iPhone—are the API settings stored elsewhere on iOS?

**Comment by thecodechemist99** [comment]
I just noticed there’s a separate `.obsidian.mobile` folder in my vault that contained the `data.json` file. I copied it to my Mac and that worked out just fine. So I think that has solved my issue.

**Comment by alangrainger** [comment]
Did you say the Obsidian configuration setting to use different config folders on different devices?

**Comment by thecodechemist99** [comment]
I don’t remember doing that, but it was set to `.obsidian.mobile` on my phone. I changed it back now, thanks for your help!
