### ISSUE TITLE
Not an issue. Just wonder which server my notes are hosted?

### ISSUE THREAD

**Issue by DelmarHuang** [alangrainger/share-note#37]
Thank you very much for this amazing but elegant plugin!! As title, just wonder. I am not a coder, so I would like to know how long this service I can use? Or it is based on your continuous update?

**Comment by alangrainger** [comment]
It's on my server. I've been running this since 2022 and I use it myself so I plan to keep it running as long as Obsidian does.

**Comment by DelmarHuang** [comment]
I see and thank you for your reply!
