### ISSUE TITLE
Shared note not getting deleted

### ISSUE THREAD

**Issue by kwilcz** [alangrainger/share-note#40]
New note deletion feature is not removing notes from the default web server.

Tried deleting it directly with API call, and it returns `"success": true`, yet the note URL is still accessible.
Sample note URL: https://share.note.sx/crddvjhf#eRSchyB0lgdl4yaFCYvszB/mAYlpDZ9MUdOpgSU8Hhw

**Comment by alangrainger** [comment]
It's cached in your browser or router. Try it on a different connection or private browsing.

This is what I see:

![image](https://github.com/alangrainger/share-note/assets/16197738/37a88f77-087f-47e1-8022-92a3c8ab1c21)

Tis gone.

**Comment by alangrainger** [comment]
Even your ISP might cache it, which is basically impossible to bypass. Nice work to check with a proxy website 👍

**Comment by alangrainger** [comment]
What website did you use to check it with? I'll add it to the FAQ/Troubleshooting

**Comment by kwilcz** [comment]
> What website did you use to check it with? I'll add it to the FAQ/Troubleshooting

It is [proxysite.com](https://www.proxysite.com)
