### ISSUE TITLE
Attachments don't display on mobile

### ISSUE THREAD

**Issue by BaseDepot** [alangrainger/share-note#45]
I'm using obsidian on mobile and any shared note will display the filenames of attachment, but the attachment can't be viewed from the share note link.

See attachment for visualization of what's being displayed.
![Screenshot_2023-11-08-09-07-57-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/alangrainger/share-note/assets/150273899/6011472a-0f3a-4b77-9bf4-1ba58d80734e)

**Comment by alangrainger** [comment]
I'll need a little bit more info here please - can you share the link to a note which isn't working?

As an example, this is a shared note and you can see the attachments display fine on mobile, so it must be something specific about the data you're sharing:

https://share.note.sx/about

**Comment by alangrainger** [comment]
Thanks, I can see the issue, will have it fixed by tomorrow.

**Comment by BaseDepot** [comment]
Will do after breakfast.

**Comment by BaseDepot** [comment]
> Can you please update to 0.8.2 and test?
> 
> I have found and resolved an issue when the image src is `http://localhost/...`.
> 
> If it doesn't work for you, please provide a link to your shared note showing the issue.



> Can you please update to 0.8.2 and test?
> 
> I have found and resolved an issue when the image src is `http://localhost/...`.
> 
> If it doesn't work for you, please provide a link to your shared note showing the issue.

You nailed it. Thanks for incredibly quick fix and amazing plugin.
