### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by Asetnozama** [alangrainger/share-note#52]
Hello,

My shared notes don't display images. In the documentation it says images are supported. 
I tried several different browsers.

**Comment by alangrainger** [comment]
Hi @Asetnozama - yes images are definitely supported (see [the About note](https://share.note.sx/about) for example), so can you provide a link to a shared note with the issue so I can take a look?

**Comment by Asetnozama** [comment]
> Hi @Asetnozama - yes images are definitely supported (see [the About note](https://share.note.sx/about) for example), so can you provide a link to a shared note with the issue so I can take a look?

Here's a shared note:

https://share.note.sx/fzdzh37z#TmGKcG/040B75rqYpRUmqb25ECecxYIq5+wdGNAqe4g

**Comment by alangrainger** [comment]
Thanks, I can see the issue, I'll get that fixed up.

**Comment by Asetnozama** [comment]
> Thanks, I can see the issue, I'll get that fixed up.

Thanks a lot and thank you for this great plugin!!

**Comment by alangrainger** [comment]
Can you please update to v0.8.3 and see if this works for you now?

**Comment by Asetnozama** [comment]
> Can you please update to v0.8.3 and see if this works for you now?

I can confirm that it works and this issue is fixed!

Thanks again
