### ISSUE TITLE
Shared note contains metadata footer 

### ISSUE THREAD

**Issue by crepererum** [alangrainger/share-note#62]
Example:
https://share.note.sx/cvhhwxoz#4NhnClbL9l9JmF6uA/p20EywNf4XPRgAK7nWEEADTSU

Scroll to the very bottom. Everything under the horizontal line shouldn't be there. This includes "linked mentioned". I'm seeing this within the app (android, v1.4.16, core module "backlinks" enabled and option "backlink in document" enabled) but it's not part of the note itself. In fact, listing all mentions might easily be a data breach / leak. Also, the footer within the app is interactive but obviously that interactivity wasn't preserved after sharing and the links within the footer are dead (which makes sense).

**Comment by alangrainger** [comment]
Tough call on this one. I have other tickets requesting that I make that section work including links.

Who is right? I might have to add a setting to turn on/off.

**Comment by crepererum** [comment]
> I might have to add a setting to turn on/off.

That sounds like a good compromise and would also be in line with the "remove published frontmatteer/YAML" option which does the same for the "other end".

**Comment by alangrainger** [comment]
The option to disable the backlinks footer is added in 0.8.5, thanks for the suggestion.
