### ISSUE TITLE
Cap & Alerts message

### ISSUE THREAD

**Issue by stoweboyd** [alangrainger/share-note#63]
Getting a message: 

{
  "code": "download_cap_exceeded",
  "message": "Cannot download file, download bandwidth or transaction (Class B) cap exceeded. See the Caps & Alerts page to increase your cap.",
  "status": 403
}

Looks like I am exceeding some limit.

**Comment by FeralFlora** [comment]
I get the same message on my article, which was nominated for best content, so perhaps there is a lot of traffic now during voting:

```
{ 
"code": "download_cap_exceeded", 
"message": "Cannot download file, download bandwidth or transaction (Class B) cap exceeded. See the Caps & Alerts page to increase your cap.", "status": 403 
}
```

Article link: https://share.note.sx/e612da498b038c3e5e367043782e2b59

**Comment by alangrainger** [comment]
Thanks, this is sorted out now.
