### ISSUE TITLE
Documentation Unavailable

### ISSUE THREAD

**Issue by TangentFoxy** [alangrainger/share-note#69]
The links to documentation are currently showing a 526 error from Cloudflare. Also, your [about page](https://share.note.sx/about) should probably link to documentation, no? Is there an alternate source to view the documentation on? (I'm specifically trying to figure out how to set note expiration.. but there is no info that I can find besides dead links.)

![image](https://github.com/alangrainger/share-note/assets/15093567/31f5f0d9-f419-44c3-85d4-abf4055b65a1)

(Edit: I did find [the documentation I needed](https://github.com/alangrainger/share-note/blob/main/docs/notes/Self-deleting%20notes.md), thankfully. Otherwise, I have just started trying this and it's working great! Thank you!)

**Comment by alangrainger** [comment]
Thanks, looks like something had gone funky with Github Pages.

Should be working now, and here's the section on expiring notes: https://docs.note.sx/notes/self-deleting-notes

Good suggestion about putting docs in the about page, thanks!

**Comment by TangentFoxy** [comment]
(Err.. it occurs to me you maybe intended to leave this open until adding a link to the about page. Apologies if I interfered with your workflow by closing it.)
