### ISSUE TITLE
note.sx is down?

### ISSUE THREAD

**Issue by jonas-sk** [alangrainger/share-note#70]
It seems like both share.note.sx and note.sx are down with error code 501

<img width="776" alt="Screenshot 2024-01-26 at 16 46 23" src="https://github.com/alangrainger/share-note/assets/7535016/6601dbc8-640e-4848-bb9f-e6b2c0180e80">

I'd really appreciate a fix for this!

**Comment by alangrainger** [comment]
Looks like potentially a Cloudflare worker outage. It's operational again,
no changes from my end.

**Comment by jonas-sk** [comment]
Thanks!
