### ISSUE TITLE
Sharing a note deletes commented out metadata in the frontmatter

### ISSUE THREAD

**Issue by TangentFoxy** [alangrainger/share-note#72]
I really hate that it reformats the frontmatter, because that breaks my workflow, but I am willing to live with that (especially since Obsidian itself breaks the frontmatter all the time). Deleting commented out data, however, I think is unacceptable.

**Comment by alangrainger** [comment]
I use Obsidian's official native command for updating the frontmatter:

https://docs.obsidian.md/Reference/TypeScript+API/FileManager/processFrontMatter

Any issue you have with that is with them, not with me sorry 🤷

**Comment by TangentFoxy** [comment]
I have raised this issue with the developers, they stick with their previous assertion that [deletion of user data is intended behavior](https://forum.obsidian.md/t/api-processfrontmatter-removes-string-quotes-comments-types-formatting/65851). There is an also [an open issue on `js-yaml`](https://github.com/nodeca/js-yaml/issues/709), the library ultimately responsible for this issue.

I figure this context is useful for anyone stumbling across this in the future.

**Comment by alangrainger** [comment]
For my own opinion on the matter, you can see I commented in that thread last year:

https://forum.obsidian.md/t/api-processfrontmatter-removes-string-quotes-comments-types-formatting/65851/11

Seems logical to do it the way I suggest there, but no response from Obsidian devs.

**Comment by TangentFoxy** [comment]
I must admit I skimmed that thread and didn't see that, thank you for giving me additional context.

(I also tried raising awareness on the subreddit, and all conversation [was shut down](https://www.reddit.com/r/ObsidianMD/comments/1g59qrx/psa_the_mods_of_this_sub_deleted_a_post_just/). For such a small issue, I'm surprised there's this much drama over it. And while writing this, I just noticed one of my comments on the API thread was deleted, which makes me question what else has been censored. I've been archiving every public-facing page related to this since things started being deleted. To be fair, it was slightly imflammatory, but that was kind of my point - igoring an issue doesn't solve it. [Archive before the deletion for reference](https://ghostarchive.org/archive/HgaCN?wr=false).)

**Comment by alangrainger** [comment]
If it helps you feel more peace about the issue, my approach is to think of YAML as programmatic access only, not as free-form plain text.

My notes are my own formatting, and YAML is there for data exchange between Obsidian and plugins, so I don't care how Obsidian decides to format it - as long as the data remains the same. (In this case, comments are not data, unless you put them into a comment field.)

**Comment by TangentFoxy** [comment]
I thought I *was* taking that approach! But yea, the big lesson I'm taking from this is to be more flexible about how I put things together, cause even though it's unintentional, the foundations will be pulled from under me.

For what it's worth, I agree, rolling your own implementation is fraught with risk because YAML is difficult to write parsing for and difficult to write correctly as a user because of its edge cases.

**Comment by luckman212** [comment]
For me, the main downside of using Obsidian's native `processFrontMatter` implementation is that a compact list of tags such as

```yml
---
tags: [foo, bar, baz, quux]
---
```
Gets munged into
```yml
---
tags:
  - foo
  - bar
  - baz
  - quux
---
```
With longer lists of tags, this can cause the body of the note to be pushed quite far down the page to make room for the frontmatter.

**Comment by TangentFoxy** [comment]
The upstream that causes this  decided they will not address it because it would require a different parser *and* goes against their goal of maintaining high speed.

For what it's worth, my perspective has changed. Anything that I am tempted to use a comment for should instead use a default meaningless value so that the *reason* I was using comments is removed. As for the changing of form to longer lists instead of more compact, I'm fine with that now because it makes cleaner diffs, and there's no incentive to change which syntax when you get to a more significant number of items, because it's already in the form that suits longer lists better.
