### ISSUE TITLE
Competed tasks are displayed as not completed.

### ISSUE THREAD

**Issue by the1gofer** [alangrainger/share-note#74]
Competed tasks are displayed as not completed.

`- [x]` doesn't get rendered in shared note as checked.

<img width="643" alt="Screenshot 2024-02-03 at 11 12 20 AM" src="https://github.com/alangrainger/share-note/assets/2140724/9fecfcae-e3d1-450a-8c48-140bbebc9152">

<img width="777" alt="Screenshot 2024-02-03 at 11 13 12 AM" src="https://github.com/alangrainger/share-note/assets/2140724/9a250421-8724-4f33-bb20-d19b6ec35f22">

**Comment by TangentFoxy** [comment]
`-[x]` is not a task, completed or otherwise. `- [x]` is a completed task. Did you make that mistake just here or also in your notes?

**Comment by the1gofer** [comment]
That’s how wove always done it, and the to rendering it as an incomplete
task, just not completed.

Jason Crews

**Comment by the1gofer** [comment]
> `-[x]` is not a task, completed or otherwise. `- [x]` is a completed task. Did you make that mistake just here or also in your notes?

Here are some sources that seem to indicate otherwise.  
- https://www.markdownguide.org/extended-syntax/#task-lists
- https://github.com/obsidian-tasks-group/obsidian-tasks
- https://stackoverflow.com/questions/47344571/how-to-draw-checkbox-or-tick-mark-in-github-markdown-table

**Comment by alangrainger** [comment]
@the1gofer this is almost certainly theme-related. Can you test this in the Sandbox vault?

You can see in the About note that completed checkboxes are functional:

https://share.note.sx/about

![image](https://github.com/alangrainger/share-note/assets/16197738/6cd79075-914f-441b-ab1e-f9a6500c22ef)

**Comment by alangrainger** [comment]
You can have a look at the docs here for how to change the theme for the shared notes:

https://docs.note.sx/notes/theme#changing-the-theme-used-for-your-shared-notes

The way it's set up is to allow you to have a different theme for shared notes and your vault.

**Comment by the1gofer** [comment]
ok, so I changed the theme to the dfault , and it's still not checking the boxes. 

![Screenshot 2024-02-06 at 4 39 02 PM](https://github.com/alangrainger/share-note/assets/2140724/43df1840-9fff-419d-ab68-7e423b7782bc)

**Comment by the1gofer** [comment]
also noticed that some of the yaml isn't getting rendered for some reason.
![Screenshot 2024-02-06 at 4 45 35 PM](https://github.com/alangrainger/share-note/assets/2140724/13f9858a-ea3e-4301-99ac-b2fce9ab644d)
![Screenshot 2024-02-06 at 4 45 44 PM](https://github.com/alangrainger/share-note/assets/2140724/d0273e3b-3ddd-40b4-8d1e-8c3bf7b6591b)

**Comment by alangrainger** [comment]
@the1gofer the dates issue has been fixed: https://github.com/alangrainger/share-note/issues/114

I still don't know what could be the problem with tasks - all I can suggest is testing in a Sandbox vault like i did before because that will rule out any plugins that might be affecting this.

I will close this issue for now, just let me know how the Sandbox testing goes and we can re-open.

**Comment by jeanys** [comment]
I have the same problem. I think I know the reason. Once the task plugin is turned on, the task will be displayed as unfinished. I don't know if this plugin can be supported, because I really need the priority display of the task.

**Comment by jeanys** [comment]
> [@the1gofer](https://github.com/the1gofer) the dates issue has been fixed: [#114](https://github.com/alangrainger/share-note/issues/114)
> 
> I still don't know what could be the problem with tasks - all I can suggest is testing in a Sandbox vault like i did before because that will rule out any plugins that might be affecting this.
> 
> I will close this issue for now, just let me know how the Sandbox testing goes and we can re-open.

I have the same problem. I think I know the reason. Once the task plugin is turned on, the task will be displayed as unfinished. I don't know if this plugin can be supported, because I really need the priority display of the task.
