### ISSUE TITLE
Front matter properties aren't displayed while the values are

### ISSUE THREAD

**Issue by the1gofer** [alangrainger/share-note#77]
The front-matter properties are displayed, as intended, but the names of those properties aren't shown.  

<img width="693" alt="Screenshot 2024-02-03 at 11 10 44 AM" src="https://github.com/alangrainger/share-note/assets/2140724/a22bee68-1406-4475-b7df-12eccc8db958">

**Comment by alangrainger** [comment]
Thanks, this is updated now in 0.8.7.
