### ISSUE TITLE
Math formulas in rows after a list are not displayed correctly

### ISSUE THREAD

**Issue by math-feng** [alangrainger/share-note#80]
For example
 ```
1. $A^{\prime}$ is linear;
2. $A^{\prime}(Jv)=iA^{\prime}(v)$
```

**Comment by poetex** [comment]
Is this the same issue as #34?

**Comment by alangrainger** [comment]
I feel like nobody reads the docs :\

It works fine: https://share.note.sx/zndza5vy#f/tnKKfrB5p4bWxu7D2ryhEfPC31pLqc+TBJd0Uo5f0

Please read the docs. Here are the docs: https://docs.note.sx/notes/latex

**Comment by alangrainger** [comment]
I believe this will be long resolved, but for reference it works fine and the solution is in the docs:

https://docs.note.sx/notes/latex

Example working fine: https://share.note.sx/zndza5vy#f/tnKKfrB5p4bWxu7D2ryhEfPC31pLqc+TBJd0Uo5f0
