### ISSUE TITLE
There was an error uploading the note, please try again.

### ISSUE THREAD

**Issue by tsouchlarakis** [alangrainger/share-note#82]
Steps to reproduce:
1. Right click note > Copy shared link
2. Browser opens, "verify if you are human" via Cloudflare

<img width="834" alt="Screenshot 2024-02-11 at 6 41 05 PM" src="https://github.com/alangrainger/share-note/assets/26070649/e099d4d9-46e7-4cc7-9bd6-5968ed9eb296">

3. Obsidian re-opens automatically

<img width="320" alt="Screenshot 2024-02-11 at 6 40 38 PM" src="https://github.com/alangrainger/share-note/assets/26070649/10f94202-a4a2-4087-a46d-bd2f237595cb">

4. Right click note > Copy shared link

<img width="328" alt="Screenshot 2024-02-11 at 6 40 54 PM" src="https://github.com/alangrainger/share-note/assets/26070649/4b02b6ae-df35-4643-b63b-d63c6d82dbe9">

**Comment by ricardiamagrees** [comment]
With or without VPN, I am getting the error on new notes and notes that I could share last week. 

The last new version 11 days ago looks minimal: https://github.com/alangrainger/share-note/compare/0.8.6...0.8.7

Did the API or server side code change this month?

**Comment by beforedo** [comment]
I have the same issue. I tried uninstalling and re-installing the plug-in. When I try to 'Connect plugin' the webpage fails to load with this error message: "api.note.sx is currently unable to handle this request."

**Comment by trottdeaje** [comment]
Same here, checking the console I see that I'm getting a 500 error response when uploading a new note or requesting a new API key. That suggests this might be a server side issue rather then client.
![image](https://github.com/alangrainger/share-note/assets/32769513/d53086bf-c5ff-4dda-b789-915383b08819)

**Comment by alangrainger** [comment]
Sorry for the late response - I've been travelling. 

No changes to the server or code for 3 months, but it looks like something is going wrong on Cloudflare D1 database at the moment. I can see there is an issue but I haven't been able to find a solution yet. Will update when I have a fix.
