### ISSUE TITLE
[Error] There was an error uploading the note, please try again.

### ISSUE THREAD

**Issue by anonymous-99529** [alangrainger/share-note#83]
Installed the plugin and hit 'copy shared link', got this error pop-up and nothing happens.

![Obsidian_UaR3KgOBLF](https://github.com/alangrainger/share-note/assets/129151549/494fb404-feb7-418a-a66d-78a880bbf1c4)

**Comment by alangrainger** [comment]
@anonymous-99529 can you please try this in the sandbox vault? 

I have tested just now and it uploads without issues: https://share.note.sx/hvjkiohb#DPHPfe6LYaqGZY3w07AlIhfAAcdK6NB7HXlyMwFU6yI

1. Open Sandbox vault
2. Install Share Note plugin
3. Click "Copy shared link"
4. Wait for the plugin setup to complete, and the note should share without issues.

**Comment by anonymous-99529** [comment]
same :(
![Obsidian_DbaK0U13Uv](https://github.com/alangrainger/share-note/assets/129151549/8b098f10-fa7e-4e58-a175-71818ec6744b)

**Comment by anonymous-99529** [comment]
I ran it again a few hours later and suddenly it started working fine. FYI, it wasn't a network issue. Thank you for your kind reply. Your plugin is great.

**Comment by anonymous-99529** [comment]
[Additional comment] I think I've discovered something: when I right-click on a note and create a share link as shown in the first picture, I get an error, but when I create a share link from the right menu of the note as shown in the second picture, it works fine. Maybe it has something to do with my location (South Korea) or language setting (Korean)?
![Obsidian_WaA5QhIDeF](https://github.com/alangrainger/share-note/assets/129151549/9dfaa28c-0cb7-4ced-b508-93c0a25cf3e2)
![Obsidian_bWA1KZwGYG](https://github.com/alangrainger/share-note/assets/129151549/cc978971-53a5-419f-9a88-d129ce4357df)

**Comment by geekiam23** [comment]
I second this. When sharing from the left menu, I get an error. If I use the 3 dots on the right, it works.

**Comment by janinko** [comment]
Yup, I can confirm the same behaviour. Can this issue be reopened?

**Comment by qt-dork** [comment]
Can confirm and reproduce the issue. It doesn't work from right clicking on the sidebar, but does work from right clicking the tab for the note in the tab bar, or from the three dot menu.

**Comment by ferileho** [comment]
I sometimes get same error on Android mobile phone. Same notes dont get this error in same Vault on Windows. Sync is by Dropbox - full sync.

**Comment by alangrainger** [comment]
Can you updated to 0.8.11 and see if this fixes the issue?

**Comment by ferileho** [comment]
> Can you updated to 0.8.11 and see if this fixes the issue?

In Windows OK, on Android still same problem.

**Comment by janinko** [comment]
> Can you updated to 0.8.11 and see if this fixes the issue?

Tried on linux and it works

**Comment by LemurTech** [comment]
Resharing does not work for me in Windows, no matter which menu/option I try, or whether I use a different or default theme. This is with 0.8.11.

**Comment by alangrainger** [comment]
@LemurTech can you please test this in a Sandbox vault? (Click on the Obsidian help icon (❓) and choose open Sandbox vault.)

I can't find any issue to reshare on Windows, so it seems possible this is related to some plugin. 

What is the message that you receive?

**Comment by LemurTech** [comment]
Indeed! **Automatic Table of Contents** plugin is the culprit! When TOC is removed, I have no issues!
