### ISSUE TITLE
cannot share png attachements anymore (Unsupported Media Type)

### ISSUE THREAD

**Issue by Tomatenmark05** [alangrainger/share-note#91]
Somehow today i realised i cannot upload any more notes with a png attached to it.
I don't know if this is a bug or if png's are just not supported anymore

I always get this error:
![Screenshot from 2024-04-08 14-25-31](https://github.com/alangrainger/share-note/assets/118772442/67e8e20b-a627-499f-bafa-6c232171690c)

**Comment by huyz** [comment]
Same with Jpegs

**Comment by alangrainger** [comment]
This looks to be a bug introduced in the previous release. Please update to 0.8.9 and try again.

**Comment by huyz** [comment]
Works. Thanks @alangrainger !
