### ISSUE TITLE
Links convert to plain text

### ISSUE THREAD

**Issue by AndyEveritt** [alangrainger/share-note#96]
Tested with version `0.8.10` and `0.8.6`

- When making a note, the link converts to plain text.
  - I have tried wikilinks and markdown links but the same occurs to both.
- If I manually share the sub note first, then share the parent note second, the link generates correctly.

My understanding was that all linked notes would get automatically shared. Is that incorrect?
If linked notes are supposed to be shared automatically shared:
- What do I need to do to fix the issue?
- Does this happen recursively?

**Comment by AndyEveritt** [comment]
I also tested in a new vault with this as the only plugin

**Comment by AndyEveritt** [comment]
If links are not supposed to be shared automatically. Would it be possible to make a GUI that appears when you share a note that lists all the unshared notes it links to so you can select which ones you would like to share?

**Comment by AndyEveritt** [comment]
Have made a fork with this feature. Let me know if you want me to make a MR
https://github.com/AndyEveritt/share-note

**Comment by alangrainger** [comment]
I'm so sorry I never replied to this!

> My understanding was that all linked notes would get automatically shared. Is that incorrect?

That is incorrect. We absolutely 100% do not want all linked notes to be shared. That would be a security nightmare if your notes were shared automatically without your input.

The correct workflow is to have the links replaced with plain text unless they point to notes that you have already opted in to sharing (by sharing them).

**Comment by alangrainger** [comment]
I'm so sorry I never replied to this!

> My understanding was that all linked notes would get automatically shared. Is that incorrect?

That is incorrect. We absolutely 100% do not want all linked notes to be shared. That would be a security nightmare if your notes were shared automatically without your input.

> Have made a fork with this feature. Let me know if you want me to make a MR
> https://github.com/AndyEveritt/share-note

Thanks - let me have a look. That could be a useful UX :+1:

**Comment by alangrainger** [comment]
I just checked out your repo - is what you've added to automatically share, rather than popping up a GUI?
