### ISSUE TITLE
Support Images

### ISSUE THREAD

**Issue by Feel-ix-343** [alangrainger/share-note#99]
👇 Please add and vote for new features here: 👇 

https://note.sx/roadmap

Thank you!

**Comment by alangrainger** [comment]
On the off chance this was a genuine request - images are already supported:

https://share.note.sx/about

**Comment by Feel-ix-343** [comment]
For my notes with an image like `![[image.png]]` share note errors.

Are you using this syntax in the demo?

**Comment by alangrainger** [comment]
Yes, that is the exact syntax used in the docs.

Have you tried in a Sandbox vault?

**Comment by Feel-ix-343** [comment]
Ill give it a shot and let you know
